import "@/styles/globals.css";
import type { Metadata } from "next";
import { dmSans } from "@/components/typography/fonts";
import { cn } from "@/lib/utils";
import { Providers } from "./_providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn(dmSans.className, "h-full scroll-smooth antialiased")}
      suppressHydrationWarning
    >
      <body className="relative min-h-full">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
